export { default as App } from "./App"; 
export { default as Home } from "./Home";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Activities } from "./Activities";
export { default as Routines } from "./Routines";
export { default as My_Routines } from "./My_Routines";
export { default as Header } from "./Header";
export { default as DeleteRoutine } from "./DeleteRoutine";
